// GENERATED by scripts/gen-model.mjs from pb/schema.json — do not edit.
//
// The database enforces these shapes; this file is how the UI knows them.
// Editing it by hand puts the two back out of step, which is the problem it
// exists to solve. Change pb/schema.json and regenerate.

export interface Users {
  id: string;
}

export interface Propietarios {
  id: string;
  nombre: string;
  telefono?: string;
  email?: string;
  notas?: string;
  created: string;
  updated: string;
}

export const PROPIEDADES_ESTADO = ['borrador', 'publicada', 'reservada', 'vendida'] as const;
export type PropiedadesEstado = typeof PROPIEDADES_ESTADO[number];

export interface Propiedades {
  id: string;
  titulo: string;
  direccion?: string;
  municipio?: string;
  precio?: number;
  habitaciones?: number;
  banos?: number;
  superficie?: number;
  descripcion?: string;
  estado?: "borrador" | "publicada" | "reservada" | "vendida";
  fotos?: Array<string>;
  propietario?: string;
  created: string;
  updated: string;
}

export const LEADS_ETAPA = ['nuevo', 'contactado', 'visita', 'oferta', 'reservado', 'vendido', 'nutriendo'] as const;
export type LeadsEtapa = typeof LEADS_ETAPA[number];

export const LEADS_FRANJA = ['mananas', 'tardes', 'finde'] as const;
export type LeadsFranja = typeof LEADS_FRANJA[number];

export interface Leads {
  id: string;
  nombre: string;
  telefono?: string;
  email?: string;
  mensaje?: string;
  propiedad?: string;
  etapa?: "nuevo" | "contactado" | "visita" | "oferta" | "reservado" | "vendido" | "nutriendo";
  origen?: string;
  criterios?: string;
  ultimo_contacto?: string;
  prioridad?: number;
  franja?: "mananas" | "tardes" | "finde";
  consentimiento?: boolean;
  consentimiento_en?: string;
  consentimiento_texto?: string;
  created: string;
  updated: string;
}

export const ACTIVIDADES_TIPO = ['nota', 'llamada', 'email', 'whatsapp', 'visita'] as const;
export type ActividadesTipo = typeof ACTIVIDADES_TIPO[number];

export const ACTIVIDADES_DIRECCION = ['saliente', 'entrante'] as const;
export type ActividadesDireccion = typeof ACTIVIDADES_DIRECCION[number];

export const ACTIVIDADES_ESTADO_ENVIO = ['registrado', 'enviado', 'entregado', 'abierto', 'click', 'error', 'simulado'] as const;
export type ActividadesEstadoEnvio = typeof ACTIVIDADES_ESTADO_ENVIO[number];

export interface Actividades {
  id: string;
  lead?: string;
  tipo?: "nota" | "llamada" | "email" | "whatsapp" | "visita";
  nota?: string;
  direccion?: "saliente" | "entrante";
  asunto?: string;
  estado_envio?: "registrado" | "enviado" | "entregado" | "abierto" | "click" | "error" | "simulado";
  mensaje_id?: string;
  created: string;
  updated: string;
}

export interface Settings {
  id: string;
  key: string;
  value?: unknown;
  note?: string;
}
